### ISSUE TITLE
Exclude .DS_STORE from LocalWar Project

### ISSUE THREAD

**Issue by moorbren** [OSUGameDev/LocalWar#25]
.DS_STORE files are auto-created by the Mac Finder and shouldn't be included in pushes. Removing it has no impact on Mac computers and clutter the project. 

"The file .DS_Store is created in any directory (folder) accessed by the Finder application, even on remote file systems mounted from servers that share files."

https://en.wikipedia.org/wiki/.DS_Store

**Comment by Nathan127** [comment]
Created a branch and PR for this issue, as well as for the Builds folder.

**Comment by Nathan127** [comment]
Merged an addition to the git ignore to fix this.
